/**
 * utils/emailAPI.js
 * ─────────────────────────────────────────────
 * Email delivery via Nodemailer (Gmail SMTP).
 * Provides generic `sendMail` and a specialised
 * `sendInvoiceEmail` for invoice delivery.
 */

const nodemailer = require("nodemailer");
const config = require("../config/env");

// ──────────── Transporter (singleton) ────────────
let transporter = null;

/**
 * Get or create the Nodemailer transporter.
 * @returns {import("nodemailer").Transporter}
 */
const getTransporter = () => {
  if (!transporter) {
    transporter = nodemailer.createTransport({
      host: config.email.host,
      port: config.email.port,
      secure: config.email.port === 465, // true for 465, false for 587
      auth: {
        user: config.email.user,
        pass: config.email.pass,
      },
    });
  }
  return transporter;
};

// ──────────── Generic send ────────────

/**
 * Send an email.
 *
 * @param {object} options
 * @param {string} options.to         - Recipient email address
 * @param {string} options.subject    - Email subject line
 * @param {string} [options.text]     - Plain‑text body
 * @param {string} [options.html]     - HTML body (takes precedence)
 * @param {Array}  [options.attachments] - Nodemailer attachment objects
 * @returns {Promise<object>} Nodemailer send result
 */
const sendMail = async ({ to, subject, text, html, attachments = [] }) => {
  try {
    if (!config.email.user || !config.email.pass) {
      throw new Error("Email credentials are not configured");
    }

    const t = getTransporter();

    const info = await t.sendMail({
      from: config.email.from,
      to,
      subject,
      text,
      html,
      attachments,
    });

    console.log(`📧  Email sent to ${to} — messageId: ${info.messageId}`);
    return info;
  } catch (err) {
    console.error("❌  Email send failed:", err.message);
    throw err;
  }
};

// ──────────── Invoice‑specific email ────────────

/**
 * Send an invoice email to a client.
 *
 * @param {object} params
 * @param {string} params.to          - Recipient email
 * @param {string} params.invoiceId   - Human‑readable invoice ID
 * @param {string} params.clientName  - Client / recipient name
 * @param {number} params.amount      - Total invoice amount
 * @param {string} [params.currency='INR']
 * @param {string} [params.dueDate]   - Formatted due date string
 * @param {string} [params.paymentUrl]- Optional Stripe hosted invoice URL
 * @returns {Promise<object>}
 */
const sendInvoiceEmail = async ({
  to,
  invoiceId,
  clientName,
  amount,
  currency = "INR",
  dueDate,
  paymentUrl,
}) => {
  const subject = `Finexus Invoice ${invoiceId}`;

  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 32px; border: 1px solid #e0e0e0; border-radius: 12px;">
      <h2 style="color: #1a1a1a; margin-bottom: 4px;">Invoice ${invoiceId}</h2>
      <p style="color: #555; margin-top: 0;">Hi ${clientName},</p>

      <table style="width: 100%; border-collapse: collapse; margin: 24px 0;">
        <tr>
          <td style="padding: 8px 0; color: #777;">Amount Due</td>
          <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 1.2em; color: #1a1a1a;">
            ${currency} ${Number(amount).toLocaleString()}
          </td>
        </tr>
        ${dueDate ? `
        <tr>
          <td style="padding: 8px 0; color: #777;">Due Date</td>
          <td style="padding: 8px 0; text-align: right; color: #1a1a1a;">${dueDate}</td>
        </tr>` : ""}
      </table>

      ${paymentUrl ? `
      <a href="${paymentUrl}" style="display: inline-block; background: #4F46E5; color: #fff; text-decoration: none; padding: 12px 28px; border-radius: 8px; font-weight: 600;">
        Pay Now
      </a>` : ""}

      <p style="color: #999; font-size: 0.85em; margin-top: 32px;">
        This invoice was generated by <strong>Finexus</strong>. If you have questions, reply to this email.
      </p>
    </div>
  `;

  const text = `Invoice ${invoiceId}\n\nHi ${clientName},\n\nAmount Due: ${currency} ${amount}\n${dueDate ? `Due Date: ${dueDate}\n` : ""}${paymentUrl ? `Pay here: ${paymentUrl}\n` : ""}\n— Finexus`;

  return sendMail({ to, subject, text, html });
};

module.exports = { sendMail, sendInvoiceEmail };
